import Head from "next/head";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";


export default function Home() {
  return (
   
    <div>
      <Head>
        <title>Erliza-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar/>

    <main className="max-w-4xl mx-auto">
      <Hero/>

      <h1>Hello</h1>
    

    </main>
  

    
      
    </div>
  )  
}
