
import Head from "next/head";
import About from "../components/About";
import Contact from "../components/Contact";
import Education from "../components/Education";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Projects from "../components/Projects";
import Skills from "../components/Skills";


export default function Home() {
  return (
   
    <div>
      <Head>
        <title>Erliza-Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <Navbar/>
    <main className="pt-[10rem] px-12">
      <Hero/>
      <About/>
      <Education/>
      <Skills/>
      <Projects/>
      <Contact/>
      <Footer/>

    </main>
      


  



    
      
    </div>
  )  
}
